export default {
    GET_SUPERHERO_ACTION: 'GET_SUPERHERO_ACTION',
    GET_SUPERHERO_REQUEST: 'GET_SUPERHERO_REQUEST',
    GET_SUPERHERO_SUCCESS: 'GET_SUPERHERO_SUCCESS',
    GET_SUPERHERO_ERROR: 'GET_SUPERHERO_ERROR',

    CREATE_SUPERHERO_ACTION: 'CREATE_SUPERHERO_ACTION',
    CREATE_SUPERHERO_SUCCESS: 'CREATE_SUPERHERO_SUCCESS',
    DELETE_SUPERHERO_ACTION: 'DELETE_SUPERHERO_ACTION',
    DELETE_SUPERHERO_SUCCESS: 'DELETE_SUPERHERO_SUCCESS',
    SUPERHERO_ERROR: 'SUPERHERO_ERROR',

    UPDATE_SUPERHERO_ACTION: 'UPDATE_SUPERHERO_ACTION',
    UPDATE_SUPERHERO_REQUEST: 'UPDATE_SUPERHERO_REQUEST',
    UPDATE_SUPERHERO_SUCCESS: 'UPDATE_SUPERHERO_SUCCESS',
    UPDATE_SUPERHERO_ERROR: 'UPDATE_SUPERHERO_ERROR',
    UPDATE_STORE_AFTER_UPDATE_SUPERHERO: 'UPDATE_STORE_AFTER_UPDATE_SUPERHERO',
    CLEAR_UPDATE_SUPERHERO_STORE: 'CLEAR_UPDATE_SUPERHERO_STORE',

    GET_SUPERHEROES_ACTION: 'GET_SUPERHEROES_ACTION',
    GET_SUPERHEROES_REQUEST: 'GET_SUPERHEROES_REQUEST',
    GET_SUPERHEROES_SUCCESS: 'GET_SUPERHEROES_SUCCESS',
    GET_SUPERHEROES_ERROR: 'GET_SUPERHEROES_ERROR'
}